## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s-labs/helm-charts/tree/923ef40a39520979c98f354ea23963ee54f54433/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Immich components

env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "postgresql-immich"
  DB_USERNAME: postgres
  DB_DATABASE_NAME: "immich"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-secret
        key: postgres-password
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

image:
  tag: v1.119.0

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: false
  persistence:
    # Main data store for all photos shared between different components.
    library:
      existingClaim: immich-nfs-data-pvc
      subPath: immich-media
  # configuration is immich-config.json converted to yaml
  # ref: https://immich.app/docs/install/config-file/
  #
  configuration:
    trash:
      enabled: true
      days: 14
    storageTemplate:
      enabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

# Dependencies
postgresql:
  enabled: false

redis:
  enabled: true
  master:
    resourcesPreset: "micro"
  architecture: standalone
  auth:
    enabled: false

# Immich components
server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
  service:
    type: NodePort
    ports:
      http:
        port: 2283
        nodePort: 30105

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      existingClaim: immich-nfs-ml-cache-pvc
      subPath: immich-ml-cache
      mountPath: /cache
