apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xen-orchestra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/icblnk/k8s_manifests
    targetRevision: HEAD
    path: xen-orchestra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
