apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xen-orchestra-ingress
  namespace: xen-orchestra
  annotations:
      kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: controller.lan
      http:
        paths:
          - path: /xo
            pathType: Prefix
            backend:
              service:
                name: xen-orchestra
                port:
                  number: 80
