apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-stack-pv
  labels:
    app: prometheus-stack
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.4
    path: /volume1/prometheus
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-nfs
