apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  superuserSecret:
    name: superuser-secret
  storage:
    storageClass: nfs-client
    size: 50Gi
  postgresql:
    shared_preload_libraries:
      - 'vchord.so'
  managed:
    roles:
    - name: immich
      ensure: present
      comment: Immich DB user
      secret:
        name: immich-postgres-secret
      login: true
      superuser: false
      inRoles: []
