apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.4
    path: /volume2/immich_media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-ml-cache-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.4
    path: /volume2/immich_media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-nfs-data-pv
  storageClassName: nas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-ml-cache-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: immich-nfs-ml-cache-pv
  storageClassName: nas-nfs
