prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nas-nfs"
          selector:
            matchLabels:
              app: "prometheus-stack"
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 20Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.controller.lan
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.controller.lan

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.controller.lan
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.controller.lan

grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.controller.lan
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.controller.lan
