apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster1
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  storage:
    storageClass: local-path
    size: 20Gi
  postgresql:
    shared_preload_libraries:
      - 'vchord.so'
