apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/icblnk/k8s_manifests
    targetRevision: HEAD
    path: immich/apps/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: 0.9.3
      helm:
        valueFiles:
          - $values/immich/apps/immich/values/helm-immich-values.yaml
    - repoURL: https://github.com/icblnk/k8s_manifests
      targetRevision: HEAD
      ref: values
      path: immich/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
