apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-immich
  namespace: pg-cluster-immich
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  storage:
    storageClass: nfs-client
    size: 30Gi
  postgresql:
    shared_preload_libraries:
      - 'vchord.so'
  managed:
    roles:
    - name: immich
      ensure: present
      comment: Immich DB user
      passwordSecret:
        name: immich-postgres-secret
      login: true
      superuser: false
      inRoles: []
