apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.18
      helm:
        valueFiles:
          - $values/nfs-subdir-external-provisioner/values/nfs-subdir-external-provisioner-values.yaml
    - repoURL: https://github.com/icblnk/k8s_manifests
      targetRevision: HEAD
      ref: values
      path: nfs-subdir-external-provisioner/values
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-subdir-external-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
