apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-immich
  labels:
    app: postgresql-immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-immich
  template:
    metadata:
      labels:
        app: postgresql-immich
    spec:
      containers:
        - name: postgresql-immich
          image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: immich-postgres-secret
                key: postgres-password
          - name: POSTGRES_INITDB_ARGS
            value: "--data-checksums"
          - name: POSTGRES_DB
            value: immich
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-iscsi-pvc
