apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-iscsi-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: iscsi-pv-4
  storageClassName: nas-iscsi
