apiVersion: v1
kind: Service
metadata:
  name: postgresql-immich
  labels:
    app: postgresql-immich
spec:
  selector:
    app: postgresql-immich
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
