global:
  postgresql:
    auth:
      existingSecret: immich-postgres-secret
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: postgresql-password

auth:
  enablePostgresUser: true
  username: immich
  database: immich
  existingSecret: immich-postgres-secret
  secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: postgresql-password

primary:
  persistence:
    enabled: true
    existingClaim: postgresql-iscsi-pvc
