apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://blakeblackshear.github.io/blakeshome-charts/
      chart: frigate
      targetRevision: 7.8.0
      helm:
        valueFiles:
          - $values/frigate/values/frigate-values.yaml
    - repoURL: https://github.com/icblnk/k8s_manifests
      targetRevision: HEAD
      ref: values
      path: frigate/values
  destination:
    server: https://kubernetes.default.svc
    namespace: frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
